"""Ungraded conceptual questions for the Commodity Swap Learning Studio."""

import hashlib
import random


QUESTIONS = [
    {"question": "A firm will buy a commodity later and is harmed by higher prices. Which forward position offsets that exposure?", "choices": ["Long forwards", "Short forwards", "Short the physical commodity", "No position"], "answer": "Long forwards", "explanation": "A long forward gains S_T-F when the commodity becomes more expensive, offsetting the higher physical purchase cost."},
    {"question": "Why is a commodity-swap fixed price generally not the arithmetic average of forward prices?", "choices": ["Discount factors and quantities determine the weights", "Swap prices ignore forward prices", "Only the first maturity matters", "Spot prices are averaged instead"], "answer": "Discount factors and quantities determine the weights", "explanation": "The fair rate equates present values, so each forward receives weight proportional to P(0,t_j)Q_j."},
    {"question": "A buyer pays fixed and receives floating. If spot exceeds the fixed price at settlement, what happens on the swap?", "choices": ["The buyer receives a positive settlement", "The buyer pays the entire spot price twice", "The swap expires permanently", "The fixed price is recalculated"], "answer": "The buyer receives a positive settlement", "explanation": "The receipt Q(S-K) offsets part of the high physical purchase cost."},
    {"question": "A buyer's swap produces a negative settlement when spot is low. Does that alone imply hedge failure?", "choices": ["No; the physical commodity is also cheaper", "Yes; every successful hedge has positive derivative profit", "Yes; swaps should never require payments", "No; because the settlement is ignored"], "answer": "No; the physical commodity is also cheaper", "explanation": "Hedge performance is judged on the combined physical and derivative position, not the swap in isolation."},
    {"question": "What does strong contango mean?", "choices": ["Forward prices tend to rise with maturity", "All forward prices equal spot", "Forward prices tend to fall with maturity", "Discount factors exceed one"], "answer": "Forward prices tend to rise with maturity", "explanation": "Contango describes an upward-sloping forward or futures curve; it is not automatically a forecast of rising spot prices."},
    {"question": "Holding other inputs fixed, what does a higher convenience yield do to a commodity forward price in the cost-of-carry model?", "choices": ["Lowers it", "Raises it", "Leaves it unchanged", "Makes discounting unnecessary"], "answer": "Lowers it", "explanation": "Convenience yield is a benefit of holding inventory, reducing the forward price relative to cash-and-carry financing and storage costs."},
    {"question": "What is quantity risk in a commodity swap?", "choices": ["Swap quantity differs from the realized physical exposure", "The discount factor is less than one", "The fixed price is quoted per unit", "The forward curve has four maturities"], "answer": "Swap quantity differs from the realized physical exposure", "explanation": "The derivative then fails to offset the physical exposure one-for-one and can create excess gains or losses."},
    {"question": "Which party generally uses a receive-fixed, pay-floating commodity swap?", "choices": ["A producer protecting selling revenue", "A buyer protecting purchase cost", "A buyer seeking more spot-price exposure", "A clearinghouse eliminating volume risk"], "answer": "A producer protecting selling revenue", "explanation": "The fixed receipt offsets low physical selling prices when quantity and reference price match."},
    {"question": "If an old pay-fixed swap rate is below the current replacement swap rate, what is the old swap to the fixed payer?", "choices": ["An asset", "A liability", "Always worth zero", "A spot-market position"], "answer": "An asset", "explanation": "The payer retains the right to pay less than the current market fixed price over the remaining dates."},
    {"question": "What remains when a jet-fuel buyer hedges with a crude-oil swap?", "choices": ["Basis risk", "No risk of any kind", "Only dividend risk", "Voting risk"], "answer": "Basis risk", "explanation": "The purchased fuel price and the swap reference price may not move one-for-one because of grade, refining, or location differences."},
    {"question": "Why does moving one fair fixed payment to a later date increase its nominal amount?", "choices": ["The same present value is divided by a smaller discount factor", "Later commodity quantities disappear", "Forward prices become forecasts", "The swap changes direction"], "answer": "The same present value is divided by a smaller discount factor", "explanation": "Under positive rates, a later discount factor is smaller, so a larger future amount has the same date-0 value."},
    {"question": "What does a forward strip accomplish that one forward contract cannot?", "choices": ["It hedges purchases at several distinct dates", "It eliminates counterparty exposure", "It guarantees physical quantity", "It creates one identical delivery price automatically"], "answer": "It hedges purchases at several distinct dates", "explanation": "Each dated exposure is paired with its own forward; the resulting fixed prices can differ across dates."},
    {"question": "Which statement about futures prices is safest?", "choices": ["A futures price is not necessarily a forecast of the future spot price", "A futures price always equals expected spot", "Backwardation proves spot will fall", "Contango proves spot will rise"], "answer": "A futures price is not necessarily a forecast of the future spot price", "explanation": "No-arbitrage carry, risk premia, storage, and convenience benefits can separate futures prices from physical expectations."},
    {"question": "A six-year swap uses observed forwards through year four and assumed convenience yields afterward. What new risk enters the quote?", "choices": ["Extrapolation and model risk", "Shareholder voting risk", "Option exercise risk", "Dividend reinvestment risk"], "answer": "Extrapolation and model risk", "explanation": "The long end is not directly observed and depends on assumptions that should be disclosed and stressed."},
    {"question": "Why can counterparty exposure grow when a swap moves in a firm's favor?", "choices": ["The firm depends on the counterparty making future promised payments", "The swap instantly becomes exchange-traded", "The physical commodity vanishes", "The fixed leg is cancelled"], "answer": "The firm depends on the counterparty making future promised payments", "explanation": "Positive replacement value is an unsecured claim unless collateral or other credit protections apply."},
]


def shuffled_choices(question, shuffle_seed):
    material = f"{shuffle_seed}|{question['question']}".encode("utf-8")
    derived_seed = int.from_bytes(hashlib.sha256(material).digest()[:8], "big")
    choices = list(question["choices"])
    random.Random(derived_seed).shuffle(choices)
    return choices

